import fs from "node:fs";
import path from "node:path";
import { SourceMissingError } from "./config.js";

/**
 * What Claude Code is keeping on disk, by category.
 *
 * Every other pillar reads these files for what they say. This one asks only how
 * much room they take, which turns out to matter: the install here is 1.4 GB and
 * growing, most of it a transcript tree nothing prunes, and the retention window
 * that bounds it is a setting most operators have never looked at.
 *
 * Pure `stat` calls. Nothing is opened, parsed, or interpreted, so this is the
 * one reader whose figures are measured rather than derived - a byte count is
 * not an estimate. The one place judgement enters is which directory belongs to
 * which category, and that mapping is declared below rather than inferred.
 */

export type DiskCategory = {
  key: string;
  label: string;
  /** What lives here, in the operator's terms, and whether losing it costs anything. */
  meaning: string;
  bytes: number;
  files: number;
  /** Newest write anywhere beneath it, so a stale category is visible as stale. */
  newestMtime: string | null;
  path: string;
  present: boolean;
};

export type DiskReport = {
  categories: DiskCategory[];
  totalBytes: number;
  totalFiles: number;
  /** Bytes under the root that no declared category claimed. */
  otherBytes: number;
  /**
   * Directories the walk could not finish. Surfaced because a total that quietly
   * skipped an unreadable subtree understates itself.
   */
  unreadableDirs: number;
  root: string;
  /**
   * The retention setting that bounds the transcript tree, when it is set. The
   * single most useful number next to a large transcript figure, because it says
   * whether the tree is bounded at all.
   */
  cleanupPeriodDays: number | null;
};

/**
 * Declared category map. Order is the reading order on screen: the things that
 * grow without bound first.
 */
const CATEGORIES: Array<{ key: string; dir: string; label: string; meaning: string }> = [
  {
    key: "transcripts",
    dir: "projects",
    label: "session transcripts",
    meaning:
      "Every conversation, and the source behind most pillars here. Bounded only by the retention setting; deleting a project's directory loses that history permanently.",
  },
  {
    key: "plugins",
    dir: "plugins",
    label: "plugins and their data",
    meaning: "Installed plugins plus whatever databases they keep. Reinstallable.",
  },
  {
    key: "fileHistory",
    dir: "file-history",
    label: "file version history",
    meaning:
      "Claude Code's own copy of every file it edited, including versions later reverted. The only record of an intermediate edit that never reached a commit.",
  },
  {
    key: "downloads",
    dir: "downloads",
    label: "downloads",
    meaning: "Files fetched during sessions. Safe to clear.",
  },
  {
    key: "usageData",
    dir: "usage-data",
    label: "insights store",
    meaning:
      "Per-session statistics and judgements written by /insights. Regenerated by running that command again.",
  },
  {
    key: "shellSnapshots",
    dir: "shell-snapshots",
    label: "shell snapshots",
    meaning: "Captured shell environments. Safe to clear.",
  },
  {
    key: "pasteCache",
    dir: "paste-cache",
    label: "paste cache",
    meaning:
      "Content pasted into prompts. Worth knowing about for what it holds, not for its size.",
  },
  {
    key: "backups",
    dir: "backups",
    label: "config backups",
    meaning: "Copies of the config file, which contain an account object.",
  },
  {
    key: "skills",
    dir: "skills",
    label: "skills",
    meaning: "Skill definitions. Small, and the thing you actually author.",
  },
  {
    key: "agents",
    dir: "agents",
    label: "agent definitions",
    meaning: "Subagent definitions, whose identity text loads every session.",
  },
  {
    key: "tasks",
    dir: "tasks",
    label: "task boards",
    meaning: "Task lists left behind by sessions.",
  },
];

/** Files whose size is worth naming individually rather than as part of a directory. */
const NOTABLE_FILES: Array<{ key: string; file: string; label: string; meaning: string }> = [
  {
    key: "history",
    file: "history.jsonl",
    label: "prompt history",
    meaning:
      "Every prompt ever typed, verbatim. The most sensitive single file here; size is the least interesting thing about it.",
  },
];

type Walked = { bytes: number; files: number; newestMtimeMs: number; unreadableDirs: number };

/**
 * Recursive size. Symlinks are counted as the link and never followed: a skill
 * linked out of another checkout would otherwise be billed to this tree, and a
 * link pointing upward would make the walk unbounded.
 */
function walk(dirPath: string): Walked {
  const out: Walked = { bytes: 0, files: 0, newestMtimeMs: 0, unreadableDirs: 0 };
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dirPath, { withFileTypes: true });
  } catch {
    out.unreadableDirs += 1;
    return out;
  }

  for (const entry of entries) {
    const full = path.join(dirPath, entry.name);
    if (entry.isSymbolicLink()) continue;
    if (entry.isDirectory()) {
      const nested = walk(full);
      out.bytes += nested.bytes;
      out.files += nested.files;
      out.unreadableDirs += nested.unreadableDirs;
      if (nested.newestMtimeMs > out.newestMtimeMs) out.newestMtimeMs = nested.newestMtimeMs;
      continue;
    }
    try {
      const stat = fs.statSync(full);
      out.bytes += stat.size;
      out.files += 1;
      if (stat.mtimeMs > out.newestMtimeMs) out.newestMtimeMs = stat.mtimeMs;
    } catch {
      // Vanished between the listing and the stat. Counting nothing is right.
    }
  }
  return out;
}

function toIso(mtimeMs: number): string | null {
  return mtimeMs > 0 ? new Date(mtimeMs).toISOString() : null;
}

/**
 * How long Claude Code keeps transcripts, when the operator has set it. Read
 * fresh and never cached, and absence is reported as null rather than as the
 * product default, because guessing here would put a made-up bound next to a
 * real size.
 */
function readCleanupPeriodDays(settingsPath: string): number | null {
  try {
    const raw = JSON.parse(fs.readFileSync(settingsPath, "utf8")) as Record<string, unknown>;
    const value = raw.cleanupPeriodDays;
    return typeof value === "number" && Number.isFinite(value) ? value : null;
  } catch {
    return null;
  }
}

export function diskReport(claudeHome: string, settingsPath: string): DiskReport {
  if (!fs.existsSync(claudeHome)) {
    throw new SourceMissingError("claude home", claudeHome);
  }

  const categories: DiskCategory[] = [];
  let totalBytes = 0;
  let totalFiles = 0;
  let unreadableDirs = 0;
  const claimed = new Set<string>();

  for (const category of CATEGORIES) {
    const full = path.join(claudeHome, category.dir);
    claimed.add(category.dir);
    const present = fs.existsSync(full);
    const walked = present
      ? walk(full)
      : { bytes: 0, files: 0, newestMtimeMs: 0, unreadableDirs: 0 };
    unreadableDirs += walked.unreadableDirs;
    totalBytes += walked.bytes;
    totalFiles += walked.files;
    categories.push({
      key: category.key,
      label: category.label,
      meaning: category.meaning,
      bytes: walked.bytes,
      files: walked.files,
      newestMtime: toIso(walked.newestMtimeMs),
      path: full,
      present,
    });
  }

  for (const notable of NOTABLE_FILES) {
    const full = path.join(claudeHome, notable.file);
    claimed.add(notable.file);
    let bytes = 0;
    let mtimeMs = 0;
    let present = false;
    try {
      const stat = fs.statSync(full);
      bytes = stat.size;
      mtimeMs = stat.mtimeMs;
      present = true;
    } catch {
      present = false;
    }
    totalBytes += bytes;
    totalFiles += present ? 1 : 0;
    categories.push({
      key: notable.key,
      label: notable.label,
      meaning: notable.meaning,
      bytes,
      files: present ? 1 : 0,
      newestMtime: toIso(mtimeMs),
      path: full,
      present,
    });
  }

  // Whatever the declared map did not claim. Reported rather than dropped, so
  // the categories cannot silently fail to add up to the install.
  let otherBytes = 0;
  try {
    for (const entry of fs.readdirSync(claudeHome, { withFileTypes: true })) {
      if (claimed.has(entry.name) || entry.isSymbolicLink()) continue;
      const full = path.join(claudeHome, entry.name);
      if (entry.isDirectory()) {
        const walked = walk(full);
        otherBytes += walked.bytes;
        unreadableDirs += walked.unreadableDirs;
      } else {
        try {
          otherBytes += fs.statSync(full).size;
        } catch {
          // Same race as above.
        }
      }
    }
  } catch {
    unreadableDirs += 1;
  }

  categories.sort((left, right) => right.bytes - left.bytes);

  return {
    categories,
    totalBytes: totalBytes + otherBytes,
    totalFiles,
    otherBytes,
    unreadableDirs,
    root: claudeHome,
    cleanupPeriodDays: readCleanupPeriodDays(settingsPath),
  };
}
