import { useEffect, useState } from "react";
import { apiGet } from "../api";
import { FailureState, RailLegend, Skeleton } from "../PillarState";

type WorkflowScript = {
  name: string;
  kind: "saved" | "generated";
  path: string;
  sizeBytes: number;
  lines: number;
  modifiedAt: string;
  sessionId: string | null;
  declaredName: string | null;
  declaredDescription: string | null;
  phases: string[];
  agentCallSites: number;
  usesParallel: boolean;
  usesPipeline: boolean;
  usesWorktrees: boolean;
  reviewed: boolean;
};

type Inventory = {
  scripts: WorkflowScript[];
  stats: {
    total: number;
    saved: number;
    generated: number;
    agentCallSites: number;
    fanOut: number;
    writeIsolated: number;
    totalBytes: number;
  };
  note: string;
};

export function WorkflowsView() {
  const [inventory, setInventory] = useState<Inventory | null>(null);
  const [openPath, setOpenPath] = useState<string | null>(null);
  const [source, setSource] = useState<string | null>(null);
  const [error, setError] = useState<unknown>(null);

  useEffect(() => {
    apiGet<Inventory>("/api/workflows")
      .then((data) => {
        setInventory(data);
        setError(null);
      })
      .catch(setError);
  }, []);

  const open = (script: WorkflowScript): void => {
    setOpenPath(script.path);
    setSource(null);
    apiGet<{ source: string }>(
      `/api/workflows/source?path=${encodeURIComponent(script.path)}`,
    )
      .then((res) => setSource(res.source))
      .catch(() => setSource("could not read this script"));
  };

  const header = (
    <>
      <h1 className="view-title">
        Orchestration <span className="accent">Scripts</span>
      </h1>
      <p className="view-sub">
        the scripts Claude wrote to drive its own multi-agent runs on this machine -
        code you did not write, which decided how many agents ran and what each was asked
      </p>
    </>
  );

  if (error) {
    return (
      <div>
        {header}
        <FailureState error={error} />
      </div>
    );
  }
  if (!inventory) {
    return (
      <div>
        {header}
        <Skeleton kind="rows" count={4} label="scanning for scripts..." />
      </div>
    );
  }

  return (
    <div>
      {header}

      <div className="stat-grid">
        <div className="stat-tile">
          <div className="num">{inventory.stats.total}</div>
          <div className="row-meta">scripts</div>
        </div>
        <div className="stat-tile bounded">
          <div className="num">{inventory.stats.agentCallSites}</div>
          <div className="row-meta">agent call sites</div>
        </div>
        <div className="stat-tile">
          <div className="num">{inventory.stats.fanOut}</div>
          <div className="row-meta">fan out</div>
        </div>
        <div className="stat-tile">
          <div className="num">
            {(inventory.stats.totalBytes / 1024).toFixed(0)}k
          </div>
          <div className="row-meta">of generated code</div>
        </div>
      </div>
      <RailLegend present={["measured", "bounded"]} />

      <p className="row-meta" style={{ marginTop: -8, marginBottom: 18 }}>
        {inventory.stats.saved} saved, {inventory.stats.generated} generated by a
        single run. {inventory.note}
      </p>

      <div className="split">
        <div>
          {inventory.scripts.map((script) => (
            <div
              className={`card list-row${openPath === script.path ? " selected" : ""}`}
              key={script.path}
              onClick={() => open(script)}
            >
              <div style={{ display: "flex", gap: 8, alignItems: "baseline", flexWrap: "wrap" }}>
                <span className={script.kind === "saved" ? "badge purple" : "badge info"}>
                  {script.kind}
                </span>
                <span className="row-meta">
                  {script.modifiedAt.slice(0, 10)}
                </span>
                <span className="row-meta">{script.lines} lines</span>
                {script.usesWorktrees && (
                  <span
                    className="badge warn"
                    title="runs agents in isolated git worktrees, which means it writes files"
                  >
                    writes files
                  </span>
                )}
              </div>
              <div style={{ margin: "7px 0 0", color: "var(--text)" }}>
                {script.declaredName ?? script.name}
              </div>
              {script.declaredDescription && (
                <div className="row-meta" style={{ marginTop: 4 }}>
                  {script.declaredDescription}
                </div>
              )}
              <div className="row-meta" style={{ marginTop: 5 }}>
                {script.agentCallSites} agent call site
                {script.agentCallSites === 1 ? "" : "s"}
                {(script.usesParallel || script.usesPipeline) && ", fans out"}
                {script.phases.length > 0 && ` - ${script.phases.join(" -> ")}`}
              </div>
            </div>
          ))}
        </div>

        <div className="detail-pane">
          {openPath === null ? (
            <div className="empty-state">
              select a script to read what it actually did
            </div>
          ) : source === null ? (
            <Skeleton kind="table" count={8} label="reading script..." />
          ) : (
            <div className="card">
              <div className="row-meta" style={{ marginBottom: 8 }}>
                {openPath}
              </div>
              <pre style={{ maxHeight: "62vh", overflow: "auto", fontSize: 11.5 }}>
                {source}
              </pre>
            </div>
          )}
        </div>
      </div>

      <p className="row-meta" style={{ marginTop: 16 }}>
        Scripts are read as text and never imported or executed. Agent call sites
        count occurrences in the source, not agents that ran: a script that fans out
        spawns as many agents as its input is long, so for anything marked "fans
        out" the real number is not bounded by the source. This panel keeps no
        record of what you have read - the list is a prompt to review, not a claim
        that anything was reviewed.
      </p>
    </div>
  );
}
